# Generated by Django 2.2.5 on 2019-11-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='runners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Equipo')),
                ('surname', models.CharField(max_length=100, verbose_name='Equipo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
            ],
        ),
    ]
