# Generated by Django 2.2.5 on 2019-11-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='runners',
            options={'verbose_name': 'Runner', 'verbose_name_plural': 'Runners'},
        ),
    ]
