# Generated by Django 2.2.5 on 2019-11-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191104_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runners',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='runners',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
    ]
