# Generated by Django 2.2.5 on 2019-11-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191104_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.AddField(
            model_name='runners',
            name='sex',
            field=models.CharField(default='M', max_length=4, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Posición')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carreras')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.runners')),
            ],
            options={
                'verbose_name': 'Clasificación Individual',
                'verbose_name_plural': 'Clasificaciones Individuales',
            },
        ),
    ]
