# Generated by Django 2.2.5 on 2019-11-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191110_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='number',
            field=models.SmallIntegerField(default=1, verbose_name='Posición'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carreras',
            name='runner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.runners'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='individual',
        ),
    ]
