# Generated by Django 2.2.5 on 2019-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191110_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runners',
            name='sex',
            field=models.CharField(max_length=2, verbose_name='Sexo'),
        ),
    ]
