# Generated by Django 2.2.5 on 2019-11-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191110_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carreras',
            old_name='runner',
            new_name='runners',
        ),
    ]
