# Generated by Django 2.2.5 on 2019-11-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191110_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Posición')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.carreras')),
                ('runners', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.runners')),
            ],
            options={
                'verbose_name': 'Clasificación Individual',
                'verbose_name_plural': 'Clasificación Individual',
            },
        ),
    ]
