# Generated by Django 2.2.5 on 2019-11-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191110_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='runners',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.runners'),
        ),
    ]
