# Generated by Django 2.2.5 on 2019-11-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191110_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='number',
            field=models.SmallIntegerField(unique=True, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='runners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.runners', unique=True),
        ),
    ]
