# Generated by Django 2.2.5 on 2019-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191110_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='name',
            field=models.CharField(max_length=100, unique_for_date='date', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Equipo'),
        ),
    ]
