# Generated by Django 2.2.5 on 2019-11-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191110_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runners',
            name='sex',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=2, verbose_name='Sexo'),
        ),
    ]
