# Generated by Django 2.2.5 on 2019-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191110_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='Puntuación'),
            preserve_default=False,
        ),
    ]
