# Generated by Django 2.2.5 on 2019-11-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191115_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='color',
        ),
    ]
