# Generated by Django 2.2.5 on 2019-11-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_equipo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='color',
            field=models.CharField(default='yellow', max_length=100, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
