# Generated by Django 2.2.5 on 2019-11-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_equipo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='runners',
        ),
        migrations.RemoveField(
            model_name='runners',
            name='team',
        ),
        migrations.DeleteModel(
            name='carreras',
        ),
        migrations.DeleteModel(
            name='equipo',
        ),
        migrations.DeleteModel(
            name='individual',
        ),
        migrations.DeleteModel(
            name='runners',
        ),
    ]
