# Generated by Django 2.2.5 on 2020-04-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200413_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='best10km',
            field=models.TimeField(blank=True, null=True, verbose_name='Mejor marca 10km'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='best21km',
            field=models.TimeField(blank=True, null=True, verbose_name='Mejor marca 21km'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='best42km',
            field=models.TimeField(blank=True, null=True, verbose_name='Mejor marca 42km'),
        ),
    ]
