# Generated by Django 2.2.5 on 2019-11-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique_for_date='date', verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Equipo')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='runners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('sex', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=2, verbose_name='Sexo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.equipo')),
            ],
            options={
                'verbose_name': 'Runner',
                'verbose_name_plural': 'Runners',
            },
        ),
        migrations.CreateModel(
            name='individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True, verbose_name='Posición')),
                ('score', models.SmallIntegerField(verbose_name='Puntuación')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreras.carreras')),
                ('runners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.runners', unique=True)),
            ],
            options={
                'verbose_name': 'Clasificación Individual',
                'verbose_name_plural': 'Clasificación Individual',
            },
        ),
    ]
