# Generated by Django 2.2.5 on 2019-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_auto_20191120_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='carreras',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Fecha edición'),
        ),
    ]
