# Generated by Django 2.2.5 on 2019-11-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_auto_20191120_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='urlfield',
        ),
        migrations.AddField(
            model_name='carreras',
            name='results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carreras.individual', verbose_name='Resultados'),
        ),
    ]
