# Generated by Django 2.2.5 on 2019-11-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0006_auto_20191121_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
