# Generated by Django 2.2.5 on 2019-12-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0010_auto_20191123_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['number'], 'verbose_name': 'Clasificación Individual', 'verbose_name_plural': 'Clasificación Individual'},
        ),
        migrations.AlterField(
            model_name='individual',
            name='number',
            field=models.SmallIntegerField(verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='runners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.runners'),
        ),
        migrations.AlterUniqueTogether(
            name='individual',
            unique_together={('name', 'number', 'runners')},
        ),
    ]
