# Generated by Django 2.2.5 on 2019-12-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0011_auto_20191201_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individual',
            unique_together={('name', 'runners')},
        ),
    ]
