# Generated by Django 2.2.5 on 2019-12-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0012_auto_20191201_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individual',
            unique_together={('name', 'runners'), ('name', 'runners', 'number'), ('name', 'number')},
        ),
    ]
