# Generated by Django 2.2.5 on 2020-01-18 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0013_auto_20191201_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrera_activa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Carrera Activa')),
                ('name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='carreras.carreras')),
            ],
        ),
    ]
